# Generated by Django 4.2.6 on 2023-10-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_singup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
